# Generated by Django 3.2.13 on 2022-05-30 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='operator_code',
            field=models.ForeignKey(blank=True, help_text='Если оператор не выбран, то рассылка по всем', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='notifications.operator', verbose_name='Код оператора'),
        ),
    ]
