# Generated by Django 3.2.13 on 2022-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_mailing_operator_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='operator_code',
        ),
        migrations.AddField(
            model_name='mailing',
            name='operator_code',
            field=models.ManyToManyField(blank=True, help_text='Если оператор не выбран, то рассылка по всем', related_name='mailings', to='notifications.Operator', verbose_name='Код оператора'),
        ),
    ]
