# Generated by Django 3.2.13 on 2022-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20220531_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='operator_code',
            new_name='operators',
        ),
    ]
