# Generated by Django 3.2.13 on 2022-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_operator_code_mailing_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='tags_logic',
            field=models.CharField(choices=[('and', 'Все выбранные теги'), ('or', 'Любой из выбранных тегов')], default='and', max_length=50, verbose_name='Логика фильтрации клиентов'),
        ),
    ]
