# Generated by Django 3.2.13 on 2022-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_mailing_tags_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('started', 'Отправлено'), ('success', 'Доставлено'), ('pending', 'Ждет отправки'), ('retry', 'Повторная отправка'), ('revoked', 'Отменена'), ('failure', 'Отправка провалена')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
