# Generated by Django 3.2.13 on 2022-05-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('success', 'Отправлено'), ('sending', 'Отправляется'), ('retry', 'Повторная отправка'), ('failure', 'Отправка провалена'), ('error', 'Ошибка отправки')], default='sending', max_length=50, verbose_name='Статус'),
        ),
    ]
